Adding Final Scenario

diff --git a/.github/workflows/LoadTest_PetStore.yaml b/.github/workflows/LoadTest_PetStore.yaml
--- a/.github/workflows/LoadTest_PetStore.yaml
+++ b/.github/workflows/LoadTest_PetStore.yaml
@@ -40,3 +40,41 @@ jobs:
         if: ${{ failure() }}
         run: |
           echo "TestStatus=Failed \n" >> $GITHUB_OUTPUT
+ 
+      - name: Result - Fetching
+        id: StoringResponse
+          # Fetch the latest test result from Neoload Web
+          response=$(curl -X 'GET' \'https://neoload-api.saas.neotys.com/v3/workspaces/${{ secrets.WORKSPACE_ID }}/test-results?limit=50&offset=0' \-H 'accept: application/json' \-H 'accountToken: ${{ secrets.NEOLOADWEB_TOKEN }}')
+          # Store the response in a file
+            echo "$response" > response.json
+      - name: Extract First Record ID
+        id: extract-first-record-id
+        run: |
+          # Extract the first record's id from the JSON response
+          Test_Result_Id=$(jq -r '.[0].id' response.json)
+          # Save the first record's id to the environment variable
+          echo "Test_Result_Id=$Test_Result_Id" >> $GITHUB_ENV  
+      - name: Download Test Result
+        id: fetch-record-link
+        run: |
+          # Access the first record's id from the environment variable
+          first_record_id="${{ env.Test_Result_Id }}"
+          # Use the record ID in another curl command to get the link
+          response=$(curl -o /tmp/record.pdf -X 'POST' \'https://neoload-api.saas.neotys.com/v3/workspaces/${{ secrets.WORKSPACE_ID }}/test-results/$first_record_id/report' \-H 'accept: application/pdf' \-H 'accountToken: ${{ secrets.NEOLOADWEB_TOKEN }}' \-H 'Content-Type: application/json' \-d '{"language": "en","timeZone": "Europe/Paris"}');
+          # Store the response in a file
+          echo "$response" > response.json
+      - name: Check Downloaded PDF
+        run: |
+          # Check if the PDF was downloaded successfully
+          if [ -f /tmp/record.pdf ]; then
+            echo "PDF downloaded successfully."
+          else
+            echo "Failed to download PDF."
+            exit 1
+          fi
+      - name: Upload PDF as Artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: record
+          path: /tmp/record.pdf
+        
